# Generated by Django 5.2.3 on 2026-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=1, unique=True)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes for this node segment.')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
