# Generated by Django 5.2.3 on 2026-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='airportroute',
            constraint=models.CheckConstraint(condition=models.Q(('airport_code__in', ['I', 'O']), _negated=True), name='airport_code_not_i_or_o'),
        ),
    ]
