# Generated by Django 5.2.3 on 2026-04-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0002_airportroute_airport_code_not_i_or_o'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportroute',
            name='direction',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5),
        ),
    ]
